from backend.app.graphs.utils.state import MyState
from langchain_google_genai import ChatGoogleGenerativeAI
from backend.app.graphs.utils.cookwares import cookwares
from backend.app.graphs.utils.prompts import CookingPrompt
from backend.app.graphs.utils.constants import MODEL_NAME, GEMINI_API_KEY
from backend.app.config.logging import get_logger

#Initialize logger 
logger = get_logger("alternative_recipe") 

def alternative_recipe_agent(state: MyState)->MyState:
    """
    Generates an alternative version of the recipe based on available cookwares.

    Takes the current recipe content from the state, formats an alternative
    recipe prompt, invokes the LLM model, and updates the state's 'content' 
    field with the modified recipe text.

     Args:
        state (MyState):
            A custom state object (dict-like) that must contain:
            - `state["content"]["content"]` (str): The original recipe text to be modified.

    Returns:
        MyState:
            The same `state` object with its
            - `state["content"]["content"]` (str)
            field replaced by the alternative recipe generated by the model.
    """
    logger.info("Invoking Cookware response modifier agent")
    content= state["content"]["content"]
    llm = ChatGoogleGenerativeAI(model=MODEL_NAME, google_api_key=GEMINI_API_KEY)
    prompt = CookingPrompt.ALTERNATIVE_PROMPT.format( content=content, cookwares=cookwares)
    result = llm.invoke(prompt).content

    state["content"]["content"] = result
    return state